name: Test Suits Routes
on: push
env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  APP_MAIL: ${{ secrets.APP_MAIL }}
  MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:16

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: 123456
          POSTGRES_USER: quizzer
          POSTGRES_DB: quizzer_test
          POSTGRES_PORT: 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Testing Routes
        run: npm test
        env:
          TEST_DB_URL: postgres://quizzer:123456@postgres:5432/quizzer_test
